{
  "suites":  [
    {
      "file":  "suite_test.yaml",
      "name":  "TestSuite",
      "summary":  {
        "overallResult":  "RESULT_ERRORED",
        "testsCount":  1,
        "resultCounts":  [
          {
            "result":  "RESULT_PASSED",
            "count":  1
          }
        ]
      },
      "error":  "Duplicate test: The combination [john|john_leave_request|view:public] in test \"Test 1\" was already exercised in test \"Test 1\"",
      "testCases":  [
        {
          "name":  "Test 1",
          "principals":  [
            {
              "name":  "john",
              "resources":  [
                {
                  "name":  "john_leave_request",
                  "actions":  [
                    {
                      "name":  "view:public",
                      "details":  {
                        "result":  "RESULT_PASSED"
                      }
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    }
  ],
  "summary":  {
    "overallResult":  "RESULT_ERRORED",
    "testsCount":  1,
    "resultCounts":  [
      {
        "result":  "RESULT_PASSED",
        "count":  1
      }
    ]
  }
}